#version 460

layout(local_size_x = 32, local_size_y = 32) in;

layout(binding = 0, r32f) uniform writeonly image2D u_out_image;
layout(binding = 1) uniform sampler2D u_in_image;

layout(push_constant) uniform push_constants
{
    uvec2 levels_size;
};

void main()
{
    uvec2 pos = gl_GlobalInvocationID.xy;

    float depth = texture(u_in_image, (vec2(pos) + vec2(0.5f)) / levels_size).r;

    imageStore(u_out_image, ivec2(pos), vec4(depth));
}
